changelog:
  exclude:
    labels:
      - skip-changelog

  categories:
    - title: Breaking Changes
      labels:
        - breaking
    - title: Features
      labels:
        - enhancement
    - title: Fixes
      labels:
        - bug
    - title: Protocol
      labels:
        - protocol
    - title: Relay
      labels:
        - relay
    - title: Dependencies
      labels:
        - dependencies
    - title: Other Changes
      labels:
        - "*"
