import Foundation

enum HostStatus: Equatable {
    case starting
    case ready
    case needsSetup(String)
    case failed(String)

    var title: String {
        switch self {
        case .starting: String(localized: "Starting")
        case .ready: String(localized: "Ready")
        case .needsSetup: String(localized: "Setup needed")
        case .failed: String(localized: "Error")
        }
    }

    var detail: String? {
        switch self {
        case .needsSetup(let message), .failed(let message): message
        case .starting, .ready: nil
        }
    }

    var tint: ColorToken {
        switch self {
        case .starting: .warning
        case .ready: .success
        case .needsSetup: .warning
        case .failed: .danger
        }
    }

    var menuSymbolName: String {
        switch self {
        case .starting: "clock"
        case .ready: "checkmark.circle.fill"
        case .needsSetup: "exclamationmark.triangle.fill"
        case .failed: "xmark.circle.fill"
        }
    }
}

enum ColorToken {
    case success, warning, danger, neutral
}

struct WorkspaceItem: Identifiable, Equatable {
    let id: UUID
    let name: String
    let path: URL
    var isAvailable: Bool
}

struct PairedDevice: Identifiable, Equatable {
    let id: String
    let name: String
    let pairedAt: Date
}

struct ActiveSession: Identifiable, Equatable {
    let id: String
    let workspacePath: String
    let clients: Int
    let state: String

    var workspaceName: String {
        URL(fileURLWithPath: workspacePath).lastPathComponent
    }

    var isRunning: Bool {
        state == "running"
    }
}

struct WorkspaceSession: Identifiable, Equatable {
    let id: String
    let workspaceID: UUID
    let title: String?
    let modifiedAt: Date
    let messageCount: Int
    var activeSession: ActiveSession?

    var displayTitle: String {
        guard let title, !title.isEmpty else {
            return String(localized: "Untitled Session")
        }
        return title
    }

    init(
        id: String,
        workspaceID: UUID,
        title: String?,
        modifiedAt: Date,
        messageCount: Int,
        activeSession: ActiveSession? = nil
    ) {
        self.id = id
        self.workspaceID = workspaceID
        self.title = title
        self.modifiedAt = modifiedAt
        self.messageCount = messageCount
        self.activeSession = activeSession
    }

    init(activeSession: ActiveSession, workspaceID: UUID) {
        self.init(
            id: activeSession.id,
            workspaceID: workspaceID,
            title: nil,
            modifiedAt: .distantPast,
            messageCount: 0,
            activeSession: activeSession
        )
    }
}

struct PairingRequest: Identifiable, Equatable {
    let id: UUID
    let deviceName: String
    let confirmationCode: String
    let expiresAt: Date
}

/// The relay setting that the running host service is using.
///
/// The endpoint is not a secret. Channel secrets are generated by the Rust
/// host only when a remote pairing offer is requested and are never persisted
/// by the macOS client.
struct RelayConfiguration: Equatable {
    let url: String?
    let isEnabled: Bool

    static let none = RelayConfiguration(url: nil, isEnabled: false)

    var isConfigured: Bool {
        url != nil
    }

    var isActive: Bool {
        url != nil && isEnabled
    }
}

/// One short-lived remote pairing offer to render as a QR code.
///
/// The payload embeds the relay endpoint, the single-use pairing channel
/// secret, and the host fingerprint. It never contains workspace, session,
/// or conversation data, and it expires two minutes after creation.
struct RemotePairingOffer: Equatable {
    let qrPayload: String
    let joinCode: String
    let expiresAt: Date
}

enum HostTextInventory {
    static func devices(from output: String) -> [PairedDevice] {
        var result: [PairedDevice] = []
        var pending: (String, String)?
        for line in output.split(separator: "\n", omittingEmptySubsequences: true) {
            if !line.hasPrefix(" "), let separator = line.firstIndex(of: " ") {
                let id = String(line[..<separator])
                let name = line[line.index(after: separator)...].trimmingCharacters(in: .whitespaces)
                if id != "No" {
                    pending = (id, name)
                }
            } else if let current = pending {
                let stamp = String(line).trimmingCharacters(in: .whitespaces)
                    .replacingOccurrences(of: "paired ", with: "")
                result.append(
                    PairedDevice(
                        id: current.0,
                        name: current.1,
                        pairedAt: ISO8601DateFormatter().date(from: stamp) ?? .distantPast
                    )
                )
                pending = nil
            }
        }
        return result
    }
}
