use blake2::{Blake2s256, Digest};
use snow::{Builder, HandshakeState, TransportState};
use std::fmt::Write as _;
use x25519_dalek::{PublicKey, StaticSecret};

use crate::{MAX_ENCRYPTED_FRAME_BYTES, WireError};

const NOISE_XX: &str = "Noise_XX_25519_ChaChaPoly_BLAKE2s";
const NOISE_IK: &str = "Noise_IK_25519_ChaChaPoly_BLAKE2s";
const MAX_NOISE_PLAINTEXT_BYTES: usize = 65_519;
const MAX_FRAGMENT_PAYLOAD_BYTES: usize = MAX_NOISE_PLAINTEXT_BYTES - 1;
const FRAGMENT_COMPLETE: u8 = 0;
const FRAGMENT_START: u8 = 1;
const FRAGMENT_CONTINUE: u8 = 2;
const FRAGMENT_END: u8 = 3;

/// Derives the six-digit short authentication string shown during pairing.
#[must_use]
pub fn confirmation_code(handshake_hash: &[u8]) -> String {
    let digest =
        Blake2s256::digest([b"Pix pairing confirmation v1".as_slice(), handshake_hash].concat());
    let number = u32::from_be_bytes([digest[0], digest[1], digest[2], digest[3]]) % 1_000_000;
    format!("{number:06}")
}

/// Derives the stable host identity displayed and verified by Apple clients.
#[must_use]
pub fn host_public_key_fingerprint(public_key: &[u8]) -> String {
    let digest = Blake2s256::digest([b"Pix host fingerprint v1".as_slice(), public_key].concat());
    digest
        .iter()
        .fold(String::with_capacity(64), |mut output, byte| {
            write!(output, "{byte:02x}").expect("writing to String cannot fail");
            output
        })
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum NoisePattern {
    PairingXx,
    ReconnectIk,
}

/// Curve25519 static identity key material generated by the Noise provider.
///
/// Callers must persist `private_key` only in Keychain, Secret Service, or the
/// documented mode-0600 Linux fallback. It must never enter Pix JSON config.
pub struct StaticKeyPair {
    pub private_key: Vec<u8>,
    pub public_key: Vec<u8>,
}

/// Generates a Curve25519 static identity compatible with Pix Noise suites.
///
/// # Errors
///
/// Returns [`WireError`] if the cryptographic provider cannot obtain secure
/// randomness or generate the key pair.
pub fn generate_static_keypair() -> Result<StaticKeyPair, WireError> {
    let parameters = NOISE_XX.parse()?;
    let pair = Builder::new(parameters).generate_keypair()?;
    Ok(StaticKeyPair {
        private_key: pair.private,
        public_key: pair.public,
    })
}

/// Derives the X25519 public key for persisted static private key material.
///
/// Keeping this operation in `pix-wire` ensures host identity validation uses
/// the same primitive as the Noise handshake and is not reimplemented by UI
/// or storage layers.
///
/// # Errors
///
/// Returns [`WireError::InvalidStaticKeyLength`] when the key is not 32 bytes.
pub fn static_public_key(private_key: &[u8]) -> Result<Vec<u8>, WireError> {
    if private_key.len() != 32 {
        return Err(WireError::InvalidStaticKeyLength(private_key.len()));
    }
    let mut bytes = [0_u8; 32];
    bytes.copy_from_slice(private_key);
    Ok(PublicKey::from(&StaticSecret::from(bytes))
        .as_bytes()
        .to_vec())
}

impl NoisePattern {
    fn parameters(self) -> &'static str {
        match self {
            Self::PairingXx => NOISE_XX,
            Self::ReconnectIk => NOISE_IK,
        }
    }
}

/// Stateful Noise handshake owned exclusively by `pix-wire`.
pub struct NoiseHandshake {
    state: HandshakeState,
}

impl NoiseHandshake {
    /// Creates an initiator handshake using a local static private key.
    ///
    /// IK additionally requires the known responder static public key.
    ///
    /// # Errors
    ///
    /// Returns [`WireError`] for invalid protocol parameters or key material.
    pub fn initiator(
        pattern: NoisePattern,
        local_private_key: &[u8],
        remote_public_key: Option<&[u8]>,
    ) -> Result<Self, WireError> {
        let parameters = pattern.parameters().parse()?;
        let mut builder = Builder::new(parameters).local_private_key(local_private_key)?;
        if let Some(remote_public_key) = remote_public_key {
            builder = builder.remote_public_key(remote_public_key)?;
        }
        Ok(Self {
            state: builder.build_initiator()?,
        })
    }

    /// Creates a responder handshake using a local static private key.
    ///
    /// # Errors
    ///
    /// Returns [`WireError`] for invalid protocol parameters or key material.
    pub fn responder(pattern: NoisePattern, local_private_key: &[u8]) -> Result<Self, WireError> {
        let parameters = pattern.parameters().parse()?;
        Ok(Self {
            state: Builder::new(parameters)
                .local_private_key(local_private_key)?
                .build_responder()?,
        })
    }

    #[must_use]
    pub fn is_handshake_finished(&self) -> bool {
        self.state.is_handshake_finished()
    }

    #[must_use]
    pub fn handshake_hash(&self) -> &[u8] {
        self.state.get_handshake_hash()
    }

    #[must_use]
    pub fn remote_static(&self) -> Option<&[u8]> {
        self.state.get_remote_static()
    }

    /// Writes the next Noise handshake message.
    ///
    /// # Errors
    ///
    /// Returns [`WireError`] for invalid handshake order or oversized output.
    pub fn write_message(&mut self, payload: &[u8]) -> Result<Vec<u8>, WireError> {
        let mut output = vec![0_u8; MAX_ENCRYPTED_FRAME_BYTES];
        let written = self.state.write_message(payload, &mut output)?;
        output.truncate(written);
        Ok(output)
    }

    /// Reads and authenticates the next Noise handshake message.
    ///
    /// # Errors
    ///
    /// Returns [`WireError`] for invalid, tampered, or out-of-order messages.
    pub fn read_message(&mut self, message: &[u8]) -> Result<Vec<u8>, WireError> {
        let mut output = vec![0_u8; MAX_ENCRYPTED_FRAME_BYTES];
        let written = self.state.read_message(message, &mut output)?;
        output.truncate(written);
        Ok(output)
    }

    /// Converts a completed handshake into ordered authenticated transport.
    ///
    /// # Errors
    ///
    /// Returns [`WireError`] until every handshake message has completed.
    pub fn into_transport(self) -> Result<NoiseTransport, WireError> {
        if !self.state.is_handshake_finished() {
            return Err(WireError::HandshakeIncomplete);
        }
        Ok(NoiseTransport {
            state: self.state.into_transport_mode()?,
            reassembly: None,
        })
    }
}

/// Noise transport state with implicit monotonically increasing nonces.
pub struct NoiseTransport {
    state: TransportState,
    reassembly: Option<Vec<u8>>,
}

impl NoiseTransport {
    /// Authenticates and encrypts one application message into ordered records.
    ///
    /// # Errors
    ///
    /// Returns [`WireError`] when plaintext exceeds the v1 message limit or the
    /// transport state rejects an encryption operation.
    pub fn encrypt_message(&mut self, plaintext: &[u8]) -> Result<Vec<Vec<u8>>, WireError> {
        if plaintext.len() > MAX_ENCRYPTED_FRAME_BYTES {
            return Err(WireError::FrameTooLarge(plaintext.len()));
        }
        if plaintext.len() <= MAX_FRAGMENT_PAYLOAD_BYTES {
            return Ok(vec![self.encrypt_fragment(FRAGMENT_COMPLETE, plaintext)?]);
        }
        let chunks = plaintext.chunks(MAX_FRAGMENT_PAYLOAD_BYTES);
        let chunk_count = chunks.len();
        chunks
            .enumerate()
            .map(|(index, chunk)| {
                let marker = if index == 0 {
                    FRAGMENT_START
                } else if index + 1 == chunk_count {
                    FRAGMENT_END
                } else {
                    FRAGMENT_CONTINUE
                };
                self.encrypt_fragment(marker, chunk)
            })
            .collect()
    }

    /// Authenticates one ordered ciphertext record and optionally completes an
    /// application message.
    ///
    /// # Errors
    ///
    /// Returns [`WireError`] for tampering, replay, unexpected order, or
    /// ciphertext exceeding the outer frame limit.
    pub fn decrypt_record(&mut self, ciphertext: &[u8]) -> Result<Option<Vec<u8>>, WireError> {
        if ciphertext.len() > MAX_ENCRYPTED_FRAME_BYTES {
            return Err(WireError::FrameTooLarge(ciphertext.len()));
        }
        let mut output = vec![0_u8; ciphertext.len()];
        let written = self.state.read_message(ciphertext, &mut output)?;
        output.truncate(written);
        let (&marker, payload) = output.split_first().ok_or(WireError::InvalidFragment)?;
        match marker {
            FRAGMENT_COMPLETE if self.reassembly.is_none() => Ok(Some(payload.to_vec())),
            FRAGMENT_START if self.reassembly.is_none() => {
                self.reassembly = Some(payload.to_vec());
                Ok(None)
            }
            FRAGMENT_CONTINUE if self.reassembly.is_some() => {
                self.append_fragment(payload)?;
                Ok(None)
            }
            FRAGMENT_END if self.reassembly.is_some() => {
                self.append_fragment(payload)?;
                Ok(self.reassembly.take())
            }
            _ => Err(WireError::InvalidFragment),
        }
    }

    fn encrypt_fragment(&mut self, marker: u8, payload: &[u8]) -> Result<Vec<u8>, WireError> {
        let mut plaintext = Vec::with_capacity(payload.len() + 1);
        plaintext.push(marker);
        plaintext.extend_from_slice(payload);
        let mut output = vec![0_u8; plaintext.len().saturating_add(16)];
        let written = self.state.write_message(&plaintext, &mut output)?;
        output.truncate(written);
        Ok(output)
    }

    fn append_fragment(&mut self, payload: &[u8]) -> Result<(), WireError> {
        let buffer = self.reassembly.as_mut().ok_or(WireError::InvalidFragment)?;
        if buffer.len().saturating_add(payload.len()) > MAX_ENCRYPTED_FRAME_BYTES {
            self.reassembly = None;
            return Err(WireError::ReassemblyTooLarge);
        }
        buffer.extend_from_slice(payload);
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use snow::Builder;

    use super::{
        NoiseHandshake, NoisePattern, confirmation_code, generate_static_keypair,
        host_public_key_fingerprint, static_public_key,
    };

    fn static_key() -> Vec<u8> {
        Builder::new(
            "Noise_XX_25519_ChaChaPoly_BLAKE2s"
                .parse()
                .expect("valid Noise parameters"),
        )
        .generate_keypair()
        .expect("generate key pair")
        .private
    }

    #[test]
    fn host_fingerprint_is_stable_and_domain_separated() {
        assert_eq!(
            host_public_key_fingerprint(&[7_u8; 32]),
            "8ddcd823c12c866d72b0df06ba9beba936ca6ba00292e0743b6aa6ba1a69fae7"
        );
    }

    #[test]
    fn confirmation_code_fixture_is_stable_and_zero_padded() {
        let transcript: Vec<u8> = (0_u8..32).collect();
        assert_eq!(confirmation_code(&transcript), "558138");
    }

    #[test]
    fn static_public_key_derivation_matches_noise_keypair() {
        let pair = generate_static_keypair().expect("generate key pair");
        assert_eq!(
            static_public_key(&pair.private_key).expect("derive public key"),
            pair.public_key
        );
        assert!(static_public_key(&[0_u8; 31]).is_err());
    }

    #[test]
    fn xx_handshake_then_transport_rejects_tampering_and_replay() {
        let mut initiator = NoiseHandshake::initiator(NoisePattern::PairingXx, &static_key(), None)
            .expect("initiator");
        let mut responder =
            NoiseHandshake::responder(NoisePattern::PairingXx, &static_key()).expect("responder");

        let first = initiator.write_message(b"").expect("XX message 1");
        responder.read_message(&first).expect("read XX message 1");
        let second = responder.write_message(b"").expect("XX message 2");
        initiator.read_message(&second).expect("read XX message 2");
        let third = initiator.write_message(b"").expect("XX message 3");
        responder.read_message(&third).expect("read XX message 3");
        assert_eq!(initiator.handshake_hash(), responder.handshake_hash());
        assert_eq!(
            confirmation_code(initiator.handshake_hash()),
            confirmation_code(responder.handshake_hash())
        );

        let mut sender = initiator.into_transport().expect("initiator transport");
        let mut receiver = responder.into_transport().expect("responder transport");
        let ciphertext = sender
            .encrypt_message(b"secret")
            .expect("encrypt")
            .remove(0);
        let mut tampered = ciphertext.clone();
        *tampered.last_mut().expect("authentication tag") ^= 1;
        assert!(receiver.decrypt_record(&tampered).is_err());
        assert_eq!(
            receiver.decrypt_record(&ciphertext).expect("decrypt"),
            Some(b"secret".to_vec())
        );
        assert!(receiver.decrypt_record(&ciphertext).is_err());
    }

    #[test]
    fn fragments_and_reassembles_large_application_message() {
        let mut initiator = NoiseHandshake::initiator(NoisePattern::PairingXx, &static_key(), None)
            .expect("initiator");
        let mut responder =
            NoiseHandshake::responder(NoisePattern::PairingXx, &static_key()).expect("responder");
        let first = initiator.write_message(b"").expect("XX message 1");
        responder.read_message(&first).expect("read XX message 1");
        let second = responder.write_message(b"").expect("XX message 2");
        initiator.read_message(&second).expect("read XX message 2");
        let third = initiator.write_message(b"").expect("XX message 3");
        responder.read_message(&third).expect("read XX message 3");
        let mut sender = initiator.into_transport().expect("initiator transport");
        let mut receiver = responder.into_transport().expect("responder transport");
        let plaintext = vec![42_u8; 200_000];

        let records = sender.encrypt_message(&plaintext).expect("encrypt message");
        assert!(records.len() > 1);
        let mut decoded = None;
        for record in records {
            decoded = receiver
                .decrypt_record(&record)
                .expect("decrypt record")
                .or(decoded);
        }
        assert_eq!(decoded, Some(plaintext));
    }
}
